enable-magisk-update = false

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
build-mode = "module"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[Boost]
apkmirror-dlurl = "https://apkmirror.com/apk/ruben-mayayo/boost-for-reddit/